const mongoose = require('mongoose');

const businessSettingSchema = new mongoose.Schema(
  {
    company_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      required: true,
      unique: true,
    },
    business_name: { type: String, required: true },
    legal_name: { type: String },
    company_logo: { type: String },
    business_type: { type: String },
    industry_type: { type: String },
    registration_number: { type: String },
    email: { type: String },
    phone: { type: String },
    contact_person: { type: String },
    alternate_phone: { type: String },
    support_email: { type: String },
    support_phone: { type: String },
    address: { type: String },
    city: { type: String },
    state: { type: String },
    country: { type: String },
    postal_code: { type: String },
    website: { type: String },
    tax_number: { type: String },
    pan_number: { type: String },
    cin_number: { type: String },
    currency: { type: String },
    timezone: { type: String },
    date_format: { type: String },
    fiscal_year_start_date: { type: Date },
    fiscal_year_end_date: { type: Date },
    default_currency: { type: String },
    exchange_rate_settings: { type: String },
    chart_of_accounts: { type: String },
    default_revenue_account: { type: String },
    default_expense_account: { type: String },
    default_tax_rate: { type: Number },
    payment_terms: { type: String },
    credit_limit_settings: { type: Number },
    rounding_method: { type: String },
    tax_name: { type: String },
    tax_type: { type: String },
    tax_percentage: { type: Number },
    hsn_sac_code: { type: String },
    tax_category: { type: String },
    tax_inclusion: { type: String },
    input_tax_credit: { type: Boolean },
    enable_inventory_tracking: { type: Boolean },
    warehouse_location: { type: String },
    default_warehouse: { type: String },
    reorder_level: { type: Number },
    reorder_quantity: { type: Number },
    stock_valuation_method: { type: String },
    batch_number_tracking: { type: Boolean },
    serial_number_tracking: { type: Boolean },
    unit_of_measurement: { type: String },
    default_price_list: { type: String },
    discount_type: { type: String },
    sales_commission: { type: Number },
    sales_approval_required: { type: Boolean },
    sales_return_policy: { type: String },
    invoice_format: { type: String },
    delivery_terms: { type: String },
    default_vendor: { type: String },
    purchase_approval_required: { type: Boolean },
    purchase_order_prefix: { type: String },
    purchase_tax: { type: Number },
    delivery_lead_time: { type: Number },
    purchase_payment_terms: { type: String },
    bank_name: { type: String },
    bank_account_name: { type: String },
    bank_account_number: { type: String },
    bank_account_type: { type: String },
    bank_ifsc_code: { type: String },
    bank_swift_code: { type: String },
    bank_branch_name: { type: String },
    bank_branch_address: { type: String },
    upi_id: { type: String },
    report_template: { type: String },
    report_footer: { type: String },
    report_export_format: { type: String },
    report_include_logo: { type: Boolean },
    user_name: { type: String },
    user_email: { type: String },
    role_name: { type: String },
    access_level: { type: String },
    module_permissions: { type: String },
    login_restrictions: { type: String },
    password_policy: { type: String },
    email_notifications: { type: Boolean },
    sms_notifications: { type: Boolean },
    low_stock_alert: { type: Boolean },
    payment_reminder: { type: Boolean },
    order_confirmation: { type: Boolean },
    system_alerts: { type: Boolean },
    invoice_prefix: { type: String },
    invoice_number_format: { type: String },
    quotation_prefix: { type: String },
    document_template: { type: String },
    auto_number_generation: { type: Boolean },
    invoice_start_number: { type: Number },
  },
  { timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' } }
);

module.exports = mongoose.model('BusinessSetting', businessSettingSchema);
